/**
 * This is a script I made and updated since CS134, just to keep track of all my pages
 * It makes it a lot easy to reference previous things I've done
 */

fileName = 'footerbar.js';

function footerBar() {

	modifyPage();
	
	footText = new Date()
	+ "<br/><a href='mailto:erl67@pitt.edu'> Contact </a><a href='https://github.com/erl67'> github </a><a href='../'> ../</a>"
	+ "<br/><a href='http://www.pitt.edu/~erl67/cs134/index.html'> CS134 </a>"
	+ "<a href='http://cs334.ericlaslo.com/'> CS334 </a>"	
	+ "<a href='http://studentprojects.sis.pitt.edu/fall2017/erl67/'> IS1059</a>"	
	+ "<br/><a href='http://cs1520.ericlaslo.com'>CS1520</a>"	
	+ "<br/><a href='http://www.pitt.edu/~erl67/1052/'>IS1052</a>";	

	newDiv = document.createElement("div"); 
	newDiv.setAttribute("class", "made by" + fileName);
	newDiv.style.backgroundColor = stringToColour(Date().toString());
	Object.assign(newDiv.style,{marginTop:"1000px", width:"20%", zIndex:"-58", margin:"0 auto", padding: "0", border:"4px outset #ccc"});
	
	newP = document.createElement("p"); 
	newP.setAttribute("class", "footjs");
	newP.innerHTML = footText;
	newDiv.appendChild(newP);

	if ((document.getElementById('end') !== null) || document.getElementById('footer') !== null) {
		Object.assign(newDiv.style,{marginTop:"100px", width:"75%"});
		document.body.appendChild(newDiv);
	} else if (document.getElementById('bottom') !== null) {
		Object.assign(newDiv.style,{position:"absolute",marginTop:"0px", bottom:"0px",left:"0px",right:"0px",width:"60%"});
		document.body.appendChild(newDiv);
	} else if (document.getElementById('page') !== null) {
		Object.assign(newDiv.style,{position:"absolute",marginTop:"0px", bottom:"0px",left:"0px",right:"0px",width:"68%"});
		document.getElementById('page').appendChild(newDiv);
	} else {
		Object.assign(newDiv.style,{marginTop:"200px",width:"80%"});
		document.body.appendChild(newDiv);
	}
}

function addGlobalStyle(css) {
	head = document.getElementsByTagName("head")[0];
	if (!head) return;
	style = document.createElement("style");
	style.type = "text/css";
	style.title = "generated by " + fileName;
	style.innerHTML = css;
	head.appendChild(style);
}

function modifyPage() {
	addGlobalStyle(
		`.footjs, .footjs a {
			padding: 0;
			margin: 0;
			width: 100%;
			border: none;
			background-color: rgba(0, 194, 255,1.0);
			font-family: Menlo,Monaco,Consolas,monospace;
			color: black;
			font-weight: bold;
			font-size: xx-small;
			line-height: 1.33em;
			text-decoration: none;
			text-transform: lowercase;
			text-align: right;
		}
		.footjs {
			background-repeat:no-repeat;
			background-size: contain;
			background-position: left;
			opacity: .9;
			border: none;
			background-image:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAAEsCAMAAAACbCSWAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAMAUExURUxpcQAAAQC36AAeJgC36AABAgC26AC36AAAAQC36ACu3QDS/wDc/wCr2AC46QC36AC36AC36AC36AC36AC36AC36AC36AC36AC36ACq2AAAAABjfgCv3QBhewDg/wC36QC25wAxPgC35wC36AAAAACp1wC36AC36ACp1gAfKAC36ADj/wC36AAXHgC36AA6SQDR/wCy4gC36AC66wDH/QC46QAHCQC36AAgKQC46QABAQBJXADS/wDj/wC36ACt2wC36AAFBgC46gC15QC15gCq2AADAwCw4ABSaADh/wC04wCt3QCp2ACo2AC66ACx4QCz4wCr2gDc/wDg/wC77QDA7gCs2wCw3gACBADj/wDH9QDM+gDe/wDj/wDU/wCYwQCo2AAICgCLsADi/wCp2AAPFACv3QAMEADL/wC46QA/UAANEQCn1AA2RADE8AARFwDb/wDR/wDE9wC86ADZ/wBacgCEpQCQtADL/QDK+ACp2QAaIgCcwwDa/wAnMwBFWAAKDgDW/wAcJACWuwBqhQCr2gAUGgAaIQDK/wBjfgB4lgAsOQBfeACr2QCn1ADM/QBwjQCiygDN/QCt1QCs2gCz5AAhKgBTaQDr/wAjLQA0QgAmMQC34QDr/wBMYAD5/wDP/gCu3QDM9wDn/wB+ngA6SgAvPADT/wDJ+ACw2wCt3AC05QBohAAZIAD+/wCUuwCr0wCk0ADE9QDD9QBNYgA0QgCIqQDW/wCv3gCx4ACfyABCVADS/wDR/QDr/wCr1QAvOwC/8QDC9gA6SwBPYwAcIwAzQQApNQDX/gApNADZ/gCJrQATGQDE9wD4/gCYwQDs/wBcdADd/QA4SAB4lgCNtABSaAA8TACQtgC67AAXHQBKXgDN/wCcxgAdJQCMsQDV/gC14wBkfwCw3gCeyACDogBuiQBjegDA7gDv/wBXbgC25wAoMwAsOABIXAB7nQBJXQCDpgDt/wCLqQAmMAD//wAsOABSaACNswC75AD//wA3RgBHWgDn/wAAAAABAUD+xcUAAAD7dFJOUwD+B9oM/h8C/QE7WEUuDQMECggUFgkFBhs3/ZY6mE8aIMQTC/41GBcx2BxMEuIQulg8JCJdJvcR1w78rVdJGSgp+h0tK0H8MaRHRjM+PEc1LzhZViBJQ0X9U0pLTlFddTv1flA/60bwQie37SC/ZedNSkBnTKGFf0BhOd94YM6z8kzde5Uv5uFumozKnSMtOZF0X3BLQNqnNtXD0ms/tDFkWTRGiLzHTCptUzmj0SZgdBtGVKu1glGDToO8d3E7Z8FseqCf17mva7ovct1ZHWpwgCaPmVKxwY0yrZdGO7t6WXmgXopZhGJdQa5To5pCenNmYpGLE8OTQmEpU2zbewAAGu9JREFUeNrtnXlYU1fawEmMJLGafcFpBzArjTGdJgMxqAkkLC27ENCq+EkFLIICdUcBl0Ld0GpxitbdWhfcqrVuVVttp9aq023a2na6TKfb9Jt95tv+uH7n3CQ3N/sNIRtz3z/6PFo53N897z3nXc9JSCCFFFJIIYUUUkghhRRSSCGFFFJIIYUUUkghhRSbMKHQQxF0hIiNGywenSOm8oTckEQopIo5bDrTZVw2GFgY6sA8MDA9JEjAxzVIlMakUCTFKFAbuGI2HT8wGwysFhhTQhrZqJSAgTn0EAjZVBq/ybQpTT564CKXp5l6XtJzRS6EIq7+pR5TmjykkdM2mZr4NCo7BB3lSPmp7+/ZdWBs8oBl7KQDV/bc+ZfAQGU71YnJphoE/7qz58qBSaEMfWDXnvdT+VLOwPWUKdY0Hf7gi7dfe23MgOW1195++61PP/0zS4h7ECZHyPrzp5++9XaoQ3/xweEmjTgEQh7f1HccYSChyr1/WiVuhBLrP++FPC4DOd5n4vMGTkjnGrtGHkfyGCFJNtL4/R2Vxk1LNao73zci2aENnYccH9ll5A58qaFLVaXn3gxxDjORWyf7NiloYpeVRkxTbOo7eQv839Dm8M1zpSppCIQ08wMTQyOkMJANPywtTFQLXRZ1OkeoTixc+sMGhEEJjXDiA2ZaKISJI+4bFgohRXavs7yk0CqRitx2fJFUYi0sKe+8J6OEQjjsvhGJ0SRkIBnrHptSBmYQ2w2Z2I4IZrFsymPrMkIaf1AJKcGuA5mZSN0rM3KzUgw82zoKbTWRw35jcniGlKzcGa/UIZmZwQ5NiY05pCDjr7bOSlewbMso0EyelGVgSXk2jQULKkuRPqv16niEEgtzSEGev/TxxwcfIi5nz14/86Rcx6eJ2XYgmtrYlNpkVNPsyGwxja+TP3nm+tmzQYx78OOPL3UgsjAQfvjujfLqsYRl0oFdfaUmlZprmzE6UEqjtuvm/ptdWiNQW7ptVrlqlam0bxew3ghLdfmNdz+0TfsgEx5bu6++TU5cgF1sFuBZEi21P753670fay2JeG6BGdr2xKWtft/aY2Eh/P19VZbUFMJiVPLVLKEYr48lFRMYCGNCRQled8VClpqvNBIfONVSdV84CBnIuoWjzQbgzhIVHub30oErAdaU6Qs6ELAOIh0LpoP1BzgbdMwX5hEflmswyxeuCwvhz0d2KXnMoAQzYDRJObkzlnQjmTJElol0L5mRm5Okwcyc4AblCbpG3u94qEEmHCWgDiQQAsyXxHywt9fY9x0GUgPsgPxEd0OHoFD5o2KKEH6CAu3oyplzEcw+o8iQuTMrR2sF9o8x9giJx8iADSM0GBuKW49sx9vYwB7ffqS1uMFoEEIbh3BsLUKETDaHKpTSWETEYFArrGVVyYvr3CwjBlK3OLmqzKpQGwyERqJJhVQOOuNhJwRqx9XwjebEVCKiaygbcaF8UTZm3FIwkzJ7UfmFEWUNOkLjJJqNfA0XVeqwE9LFUonZVFba/zAR2Tblwu3X5yEOLgqS5zBCwV/Ne/32hSnbCI3TX1pmMkuk0I0OOyFbqDYf3vz5mdu/JCLLXl97cZjjEwSf3/hPxuP+NOzi2teXERrn9pnPNx82q4XsCBByWC+d+Gv3rVvjCMrTK50ainx87fK1jxGnpq58mugwt251//XESyxOBAhFmp49HwQTX5Hhvrz2b/Z90477KmXBxHs+2NOjEYWfkCmWmK58BuNvFKLiAGxePLu+/25//ezFzbiFh5jAuNpnV0wSEBsNOyGVv2nXG0F7xeCjex7sgDmpqtQcsDs+H3wEioG8sWsTnxp+wgSqsmvkIwPw+y/thVaMgWaAFs7eSwPw5x8BhjE1At8hT5n2aLCEFKTm2I2j/To+yBSJuXxd/9Ebx2qCjF0AwkfTlLwYJUTy/vHqkYIcBQ2Y2nQRTZFTcOTVf+QhQ4gQBHmuLSjIUcI0EUhoKXMKFlx7fmjNIQXpWPtTaaKex6azefrE0p/WdgQbYItxQvDvN7QXlKkMPDHPoCoraN8wgBGiRkgsestAdpTXl6n0LL2qrL58h91kCBhljo85dCAeBIhWlRUAHrT/PCUO5pCC1H20e/cE37L7o2FY8GJueS+waXrL52J/M+wjvz+7+6M67C1Ei5CBrH73cnv12Ek+JPmr9q+XY0Cd7fsu7GvvxP68/Ov2r5J9/ejY6vbL767G/aZozeHya1d7i+VpXqWwcHRR7+1T4zCkj26cuvER9qdxp273Fo0uLPT+w/Li3qvXlsfAHC5fe6FUl6LwLkaV1VI7/VQ39t398d0/Yt9l96nptRaryujjZ1N0pRfWLo/6HALCrdsa+FyedxFKDUpt2/QVdY7AefaObEcwt27F9Dat0iAV+vhZLr9h29aYIPzlw6kstq/wLchXSHRtrWsasVl0zGDjmtY2nQTmL3wIm5X68C9jhpDup3CMy9e2HXp8JYZmA135+KE2LZ/rp2SLHjOEW7fpDBw/g4gA4qxVi/G+BPA1Fq+aBQBFfh6OY9DFiJbuLciSUP2E51HE4pb1GRgiBclY31LsH5BJp0qyCvbGAuHqtUfvmg3+wvMgccFPL57xjH2NgevNMzOK0/lSf4BsscF89+jaWNgPm88vq7ek2DOhPhEF6UXJT01Fg1IU2dSnkovSBf4AYeY0xVK/7Hxz1PdD8ADdn1TUW8yOrK4vRGVD7eyNsHgGlNhsnF3boPQDiGaMzZb6ik+6nR9v5AipbpY3BYbnSwqxrK4PRJoyK3f2IuRnlJ8hi2bnZilpfgDRjDEoJ1qUjVudbIQRiNMwqYJRI11ibSBcOAZkdRsU/jQVFrJl5Y59A/kZ8sbY3Cy3MjcPDVU0gIzxGCx0bI+1wQeIQDRR7BFNBJHCcTCra9b71lQmXcxSNBT/eB25/mNxg4Il9v0PQfmwGWaMx7lGHG3RxAjESxPEelPfZ24xb1DdtaiioNDqR1OB6rEU2rL93+8v0wJAP/+MxrcWFlQscq8Gy0Q+6zPpxZHIWxiabr53T+aWDqQgO+ZPa0v3o6nw2SVJTXeakiS+3wOqoelt0+bvgJrh8htk99672WSIRN6CzRXkLP1ujtsbdmiqSi/0paloYYlGrXGUoHjVUKFe5UVD4a+f893SHCU3ErknOtVgLhx5dbznM9RsRDVV6huAIxKLxSKO71cgRTV0Y43n+xt/dWSh2UCNRP4Q1GirrfLTM+cOd9dUGTIvkKYy/fS5YBo6D/EYefjcmaflsAw3EjngBLSAK39K9TNeNHX5mha/muq3KAXV0JY1y71o6DPVoDpFbbNjI1CLgVYAZdW2bBnmRVPXPeZ/TU3wv4Y6q25w723YlpbaLKzCKCLVJqCKS5neVrl1rseaKrt3cBmqqdSg+jyYHCqqocsOehlx7tbKtnQl1pISkYoh25oA6pyeWun5xlevaKmFmhpEPxLQCqChtS0rVntqxcqnQP0Ufv2KTE0U0/ZMucSeKbCG+n1fubb3xYxw1RfTvvItO4j40isWMU0FGsrypfOIXed5uJEiVtdmWxvyva8ND25ZiK4NLg4EE1ZacmBFJtPF7UDXrYVbHvS+buW7r1uRq9wLsL7bqg+xZ4O9mrCQ3QBL2Z19kVBDJcHtPZGsTfSzRyNgj66crEU1Fc6diAo6KpWq1J6enlSVEnRcUkVwLlEN1U4GlYvDEaL2Q0SrLzFPwKudtWUV0FQ9lyoWC2kafkqqqUvev7lvc7+8y5SawtfQhGIxlasHGrpqi28b0HNnjXB9KfTmfNrK0BLRKSRqvsKsHSUf8eSjyT/85bO//JD86JMj5KO0ZgVfLVHofGio3Y73Eo6LdAWtTVNnQX/HU1M7Z1YWlWU15KS1bft87H1bfr6jeSoytXnHz7fcN/bzbW1pOQ1ZZUWVMzu9aCjwxWb5sHAjXiPs22eFdbKnJh6trz89qXrBCxMerMFi3jUPTnhhQfWk0/X1Ryee2u45+3796chXQaNrqtlS5ampYFIbP7yxd++KjWPqhqPIFOy/w+vGbFyxd++NDxvhlHloaJXF7Mt+j0adN9oPA2NHLyIMd03N69y9OgOlxYHY/5CxendnnruGMpAXYVzL6NMHi0oluyP+V+EsO3QG4rBpc690ozj/Ae6VZC+q8B+bjE6tvj2GW5X8SrfHV8Vg+KqxlDEYHl9u9yvJVf7jy9HqRrBpavH0BRvcpyWIog0KsmHB9GI/GhpNQrT7DvY2lT+XPcCORaChz5WjPVFUf15J9DpK7P1poPWgGWHIguaTwRJboKGJfjMgCdHtmbFrauvOAbRow6bvna2BNDTahGjjKyiQLSl/OVhNBRr6cnkJKLFlUQP5zdHte3Jo6uwX6oLRVKChdS/MJqCh0Se05zYbig8d6SCuqUBDO44cKm5ICaihsUDo1NQJeQQ1FRg+EwhqaEwQAkSRFB4mMHs9IU2FGrp+NjyWQCoiFLqKhf5DoKmalKyiQ88SaDqAbQrPHirKStHwCIYfY6LDEmqqEjQdtO+eGnAOp+5uB20KSmIaGjOE9tbYwt72D+f4LZOlIHM+bO8tDKphNla6ZGFyI7H06N93+11uGMjuvx8tTdQEEyCPmT5gJpun1hWd6wT9287mJxczm0IBfd2d54p0al4weZzY6XRmsrmKTVeu+21zy0SuX9mk4AaVqIqhXm54VNiJD+7VZACpcefMzED/+t4HJ4I9rCuWutVB4aXud789+ZsVF/9w3vUQGJBxOf+Hiyt+c/K3vwPNUJyEeCWkA+vGenj/5tNnXn91vBvhr159/czpzfsPW4ElQ49bQpif4ielmvK37Vv7K3fCtfu25ZtSk/gueaW4IwRpF9jYntV/1Avh0f4s2IIuDTYhHlNayuGxwBxqy3zMYZkWzCGLx6HH93eYdbe/5KedHt/hg6/uPFPSfzcrvr9DcHSmrrT+6DdHvj5/7UE3wmHXzn995JujvaU6cHhlvBIyRYamE3+qqWtsnNPYmO22H2ajf1tX86cTTQZRvO6HTKrEtOetADbNW3tMEmrcEvIEm3adRfIoPu1SSh5ydtcmJS9uCYXGtAO/DuBb/PpAmlEYv4Qp8kkPBSKcJE8RxvUcnh3Sc8hTot+hH/8w3r9DsJb2BVxLwUHA8buWQv/wTzb/MMOXf/if8e0fSgWB/UOtIH5tmgRYhhrQP4SFo/HsH7L4xkQ/vkWiEfoWcewf2qr19EmW+r0ehHsLLEl6lyq+OCS0FVyCTkLdw195eE9fPazTiNlupZjxR+gY5oGJHoS/eGCAj0YSkoQkIUlIEpKEJCFJSBKShCQhSUgSkoQkIUlIEv67EsLbLmAHs6fYI2nxTsiEPb4sg8ZTQE+zEN6DGueEaFWQQJWqTXcXbU+iUQKrZeKdEBQDq96/uXnzkx5iz0rEOyGdpzd3gfzSb/7DQxyZJXZ8E7Klyve/XZlhSxK6iT07GOeEHFbTzb/l+c3wxjuhoWfzO3mITOZxJYUMZOl/vWuUkhfvhHrT0nem+ppDtNIizglFatPSL6f6qiWZN1aewo1/wice902YLE8iCUnCGCccO7QJwVo6aUispf4Ih8B+6J9wKNg0XgjzsvNsko0MBbvUgxDcf/CHT5Ys+fLLL9/527f/o1XSOEOP8Njl+Wc+f+KJpdA/BAchselDj3DvhX6LyWTqabJ1xAw1Qgby+3NF6Qq1Wq8x0GCchjn0CNHLn+GlzjxwrbNIxBFrdLVfDbE5HKFVqvWYSMAVVh61iUPiO8TEW/9hnK+lC86cXuqUJ6bd9qwRDoFQEDbCR7u89A142w/Pf3JxDS7mtmbNxU886rwHTMgEV0w+Gh7CdS2FKVw6IZvGi7if4zZgQjo3pTAst8dTkN9PHJFq8Dio0Z9d6q9XZqCEdJEhdcTEY2EhPNbea1F43Lvhg1CGl0EkBOdtKCy97YNHaH5gIkbYffEXuZ6Xw0R2DtEra3J/cbEbI5z4gDkUQql58rk3sSua6pacK053v9M+koTw8EJBevG5JXXY5VFvnptsloZACD7qVQ5CeOTq4paidKUrokjvO5o4yIQQUJle1LJ4jvOR3lzlbfkjPiQPbD3HsdYscPLt+hm1Wa73b3A02s3vRIQQvQMkq3bGeueJvpnIcbBJ85gDJxTreza/l427+ij7KXALjhF/HhDHkAqj+uEnhOcWGcFtPE9l4y5Iyn5vc49eHAIhh5bSteu7Ghxi3sbq3JwUgxORTUu6eTIj+IthgyWEZ/mn5ORWb8zDAdZ8t6srhcYZOGECuNnWOnrSYudh8OCypuceq8pJciLShXzT0v+eKqOElxACJuVUPfbcPZkTcOXiSaOt4AbegQM6boVb0uhEpCATKqZYVBrHsUBMcHtY4YH7gzxFMFhCcGCRRmWZUjHBeXQoOARtScDb6YjtP9pZrSu6nYjwwtSCMrPG3nIGrizh64rHrq8JCjFIQtAEpzGXFcArWp2AzStaAaA0NEA7Ytv0Z592AoBI9syS/ES90IZou1StZfHKYBCDIwRvUZ+YXzJzHv4hnn4WXIEZOqBNUa2jp+3EnWuRiWzYWlIIb32Bo4O7quA2vBCnyoNMCI4NUycWlmzd4GwpBj+/c9poa6gq6hifK7HKK+c/j0d8fn6l3Cqxjc+0qfIhnCoPKiG86NP2ADhA+wNwBgEQe4XLcK8w0/UVelHlwSN0KhHu129Y5lSiwUF0fAYy7He4fAbwKXSuTzFYhM63l+k8StKxEAwSoMtSJsMesXvFIRsi00WVMweV0PYFtOG/AJnbYj54iLbtiOGyHaGuhgMRqHLlMoK3whMktK9iq5bU4Xcr+4Y8mIDojuvNpGgpanC4GrYVvQC/oodMiDoTDS47EWZU8diDCujLLFyfDF0NmwUHv1a3XRl95XahBE8IbW3gTCSv92sYDyaiu2nvcDXsv86pyoEPZSdCCF+qj9/ICgOgV/cM3Aq7qLoKe6Oe1jEFGdd56dLcuZcuddYhlOAIbVpTVb1oqoziz0EdXEQ3F9v+VViScIjwoTBVZiA73r3c/lgFuOh+e5DxUvR1Wdy+fG9BhkFFtK9sa1xWtk7cygbvKbYrlj3IuuHyN71FteCi+yCj+g6V7/S5eocLEe5OrVtcXI2HygvyzXoMEa/K4DaO9t67Wm3phSAzMwBQb84vKH8ID9i9pRXuwGEEtFsYusnTn12Ot/J34CwMbIFHVRkQVhTp+IL0bTODyls4rKgd+F+z/Nnpk3WD4UwQMINHT1swHv+7NyyrLLSquXhXw6bKDOS/ZkxWsQwgsBwMoRfzAVwftQBYwhJuuAFtN1haSyvnd+Bdje04V8NuSR4CqpwJCCfJk2is4HLADmdiO96Z6JhfWWpVRwDQ6a29iH/Bw3ZOc2qQU5Wzkbd/TDMGSWj78Wk7h+F/wYtbB9WZCITIc9hnTjt83ClXVwOocuX/HkeQt/s2KaVBEdqdiVPj8Lb2vJkF4FPnRQbQ4WrUu0dNDs3Cshqoq1H45PQvkE//r0fCDYYQzUwAd7rZNTJUP9jOREBEg6rMzdVofLylGNuNUVUeVbrni0/vNBl4xAltVkVxy+ONbs5EmcoQQUCnq/HIcLyr8cIMcO09C0PUG3u0pj8bJVIq4WoTuJ0qG2pnvIB3JoY/Eh5ngpirsQ7vamQ8k1zb4HA14ClYeoHAoJdSRUQJUWeioTb5mQy8M7EuXM5EYERjFvowOMP/fryrwRbzuDR40hWHIKHDmbgf70zA14aNGWFEeOE9UCi8qzEcuBoWzNUAPXugXohNJ1i5h+qFBTgTeNWvgaofNmeCiKtR3PIKztWg3HsZdTUc8XDbLdxoKjkgIVy+oDPx8j1c4H7OK7jlK/KIqH0265C7q4Eu7PhHAqlkL4Ru6WmYmQBbkJszsQZsQWF1JghF+lq3uGzOB8vdN2e6NGn0OXfC8edKVbj0tN2MKD/oYkbYnAkRPSFqYjewjqzGW5BjoKuBN7CYQkV+63E3wuOt+biTWdH9EzgTY/DW7uoj0yLhTBBzNbbjbcgOm6uBPRmTxzdd6UDwieI8pGOXiY+lp1FzHjgTHfhhtkfKmQiY1fD2bJX4ZwPnmKbuPzkON4lAAU/uT8XOLbXbsV7fEyfKgE5n1Y9+MTlSZc7Sq6uxfwFOL726NEcptZthvnVdL4w+oC3g4G2NmOUMONCpBlXhaWyK4CSfTlMZbOfp20Ijs3ysV8yEhJhA9LXO27Ma6EsA2asOe/CmA2aOHJEdNMMK9pxmL3tObADa7HAQF/O+V9OZLktlJrgeCL/Ywk3Vm90A4neRtrUD2uHu9tZKvL1l3+4q4OneZyucGyZm+630ZfvFECKwmavXudnM+JC/EMQ/cw9cR64fyAXxVSGH6fw5N/t9Hc5+jylERZY/v4eJ3ouYv//7/fnoPYdMfz5YliLWAB2+a5Gn7wrUjecI+bMEqp47PSrHPYfw+wXK7cePji1EW5zULf7wMog/JGkciGIuS6PWsLhiB6AmCcRCXvaIhUTT1vaLaFv2fceQgMMoEovFIrZjC/ERzxIEcZFexBF9xwFxDiMTbyh4j0nGJGCCvSQDjeVmBorleokrZ9rjylG3tQO6Gl7j8W7FPWhA1UtuIBacCSIh/4A5FZ/5nYgF7kN3NbznxZjODxZos+8cXUwLukTacpsy99ymfRYdwQ+XKiA0zxo7tnYAO9xLfnoNlp/2mytnxwFgoBoDup96h7iYQWfI33udCFVEDVCzEjeI3mt9UjQscNuzv7qj+EH0Wq9VZbGqrJYqP7VjcYSIuhruNXcVvf13+3srvNT/xaIzQcjVWIivm6Qgu9v3/bSvfbdrS8HCmHUmiIT8Xaq/waZw6fLXly+5VAEBZ0Ib7bh2SIju9cs7Xt3hs5Y6HhE9atAplGZnaWbmYLYURMtI9aj+piAUj54GTtwC4ntBGE5EpzMRySqg8Loa3qq/Hd5/nAN67cny1h8W74ge1d/OHr/4B/TaG+nZpxn/iC6NDOFsKYiakYqv/mY4nAnxUAF0q/4Od0tBFF2N9KKFIEuYBzKLC4G7P7QAseqike80I83vjJwVp85EAEQYQZT3ffvFt31yXSwH7kNyNSQq0+ETh00qiVRETxiCQhcJDRLlS0qJQTg0AaGRCipOpVx4t2rCEBV4TQS4EWIIfoKkkEIKKaSQQgoppJBCCimkkEIKKaSQQgoppJBCCimkAPl/L9udtmtA+6EAAAAASUVORK5CYII=);}`);}